# Generated by Django 3.2 on 2021-04-27 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('picture', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=120)),
                ('annee', models.IntegerField()),
                ('cv', models.URLField()),
                ('diplome', models.CharField(choices=[('SUP', 'Superieur'), ('SEC', 'Secondaire')], max_length=5)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.employee')),
            ],
        ),
    ]
